"""SQLAlchemy declarative base and shared column conventions.

Two conventions are enforced here rather than left to each model, because both
are the kind of thing that is trivial now and expensive to retrofit:

1. **Explicit constraint naming.** Without a naming convention, Alembic
   generates auto-named constraints that differ between environments, and a
   migration that drops a constraint by name then fails in production.

2. **UTC timestamps everywhere.** ``TIMESTAMP WITH TIME ZONE`` with a
   server-side default, so a row's creation time never depends on the clock or
   timezone of whichever process inserted it.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Predictable constraint names, so migrations can reference them reliably.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """A UUID primary key generated by the database.

    UUIDs rather than sequential integers for two reasons: they can be created
    before a round trip to the database, and they do not leak row counts or
    growth rate through URLs.

    ``gen_random_uuid()`` is used rather than a Python-side default so that IDs
    are consistent regardless of which process or language inserts a row.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )


class TimestampMixin:
    """Creation and update timestamps, both timezone-aware and server-side.

    ``timezone=True`` is essential, not decorative. SQLAlchemy maps a bare
    ``DateTime`` to ``TIMESTAMP WITHOUT TIME ZONE``, which stores a wall-clock
    reading with no record of the offset it was taken in. Everything then
    appears to work until two processes in different regions write rows, or a
    daylight-saving boundary passes, at which point ordering silently breaks.

    CAIRN is particularly exposed here: file 12 §3.2 depends on distinguishing
    when activity *happened* from when it was *received*, and briefs are
    assembled by ordering on time. A naive timestamp would surface as a brief
    reporting the wrong day's work — visible to the customer, and hard to trace
    back to a column type.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
